[package]
name = "hello_world"
version = "0.1.0"
authors = ["Shing Lyu <shing.lyu@gmail.com>"]

[dependencies]
hello_macro = { path = "../hello_macro"  }
hello_macro_derive = { path = "../hello_macro/hello_macro_derive"  }
